### ISSUE TITLE
Binary Packing

### ISSUE THREAD

**Issue by huyidao4444** [posener/gitfs#29]
### 1. I wan Using Binary Packing. so I test with the following code

```go
func main() {

	ctx := context.Background()
	fs, err := gitfs.New(ctx, "metest/public", gitfs.OptLocal("."))
	if err != nil {
		log.Fatalf("Failed initialize filesystem: %s", err)
	}
	f, err := fs.Open("go.mod")
	if err != nil {
		log.Fatalf("Failed opening file: %s", err)
	}
	io.Copy(os.Stdout, f)
}
```

### 2. It can run successfully before Using Binary Packing。The result is：

```
module test

go 1.13

require (
        github.com/posener/gitfs v1.1.0
        golang.org/x/tools v0.0.0-20200115044656-831fdb1e1868 // indirect
)
```

 

### 3. Using Binary Packing  run successfully  .The result is：

```
github.com/posener/gitfs/cmd/gitfs/gitfs .

[gitfs] 2020/01/15 23:06:19 FileSystem "github.com/posener/gitfs/cmd/gitfs/templates" from binary
[gitfs] 2020/01/15 23:06:19 Loaded file binary.go.gotmpl in 0.0s
[gitfs] 2020/01/15 23:06:19 Loaded file test.go.gotmpl in 0.0s
2020/01/15 23:06:22 Encoding project: metest/public
[gitfs] 2020/01/15 23:06:22 FileSystem "metest/public" from local directory
2020/01/15 23:06:22 Encoded path: go.mod
2020/01/15 23:06:22 Encoded size: 332
```

### 4. go build the test code ,and run it .run time error is:

```
panic: Failed decoding project "metest/public": decoding gob: gob: encoded unsigned integer out of range

goroutine 1 [running]:
github.com/posener/gitfs/internal/binfs.Register(0xb12c6f, 0xd, 0x1, 0xb2ec8f, 0x14c)
        /home/star/gopro/pkg/mod/github.com/posener/gitfs@v1.1.0/internal/binfs/binfs.go:61 +0x203
github.com/posener/gitfs/bin.Register(...)
        /home/star/gopro/pkg/mod/github.com/posener/gitfs@v1.1.0/bin/bin.go:10
main.init.0()
        /home/star/gopro/src/test/gitfs.go:7 +0x54
```

**Comment by posener** [comment]
Hi @huyidao4444 thanks for reporting this!
I was able to reproduce by installing the gitfs tool from master but using the library at older (v1.1.0) version.
This is fixed by having a new release from master (worked for me).
Can you please update your module dependenct to v1.2.0 and verify that you no longer has a problem?

**Comment by huyidao4444** [comment]
### I update my gitfs module from 1.1.0  to v1.2.1 .The problem is solved. Thank You! 
### It's a wonderful tool！
